solicitante:
  nome: "siga"
  sobrenome: "DevSecOps"

homologacao:
  pre_aprovado: true
  restricao_horario_inicio: "07:00"
  restricao_horario_fim: "23:00"
  
treinamento:
  pre_aprovado: true
  restricao_horario_inicio: "12:45"
  restricao_horario_fim: "23:00"

producao:
  pre_aprovado: false
  restricao_horario_inicio: "10:00"
  restricao_horario_fim: "23:59"