swagger: '2.0'

info:
  version: "1.0.0"
  title: ExApiV1
  description: API para o Siga-Doc

basePath: /sigaex/api/v1
schemes: [http,https]
consumes: [application/json,application/x-www-form-urlencoded]
produces: [application/json]

tags:
  - name: auth
    description: Autenticação
  - name: download
    description: Download
    
securityDefinitions:
  Basic:
    type: basic
  Bearer:
    type: apiKey
    name: Authorization
    in: header

################################################################################
#                                   Parameters                                 #
################################################################################
parameters:
  sigla:
    name: sigla
    in: path
    description: >
      Sigla do documento com a via ou volume. 
      O formato da sigla é DDD-UUU-AAAA/NNNN, onde DDD é o acrônimo do órgão (tamanho variável), 
      UUU é a espécie do modelo do documento, AAAA é o ano de emissão (4 dígitos), 
      NNNNN é o número sequencial do documento naquele ano. Os hífens e a barra são opcionais.
      Eventualmente ao número pode ser adicionado um indicador da via ou volume (mobil). PD-EXP-2020/000123, 
      SAA-MEM-2019/1254-A, GOV-PRC-2018-3548-V01
    # Padrão baseado em ExMobil.setSigla
    pattern: ^([A-Za-z]+)?-?([A-Za-z]{3})?-?(?:([0-9]{1,8})|(?:(\d{4}?)\/?)([0-9]{1,8})(\.?[0-9]{1,3})??)(?:((?:-?[a-zA-Z]{1})|(?:-[0-9]{1,2}))|(?:-?V([0-9]{1,2})))?$
    examples: 
      - PD-EXP-2020/000123
      - SAA-MEM-2019/1254-A
      - GOV-PRC-2018-3548-V01
    type: string
    required: true
  sigladoc:
    name: sigladoc
    in: path
    description: 
      Sigla do documento sem via ou volume. 
      O formato da sigla é DDD-UUU-AAAA/NNNN, onde DDD é o acrônimo do órgão (tamanho variável), 
      UUU é a espécie do modelo do documento, AAAA é o ano de emissão (4 dígitos), 
      NNNNN é o número sequencial do documento naquele ano. Os hífens e a barra são opcionais.
    examples:
      - PDEXP202012345
      - SAAMEM201912345
      - GOVPRC201912345
    type: string
    required: true
  siglamob:
    name: siglamob
    in: path
    description: 
      Via ou volume do documento (mobil). 
      Se a espécie for do tipo expediente, deve indicar a via do mesmo, uma letra maiúscula de A a Z exceto as letras V, X, K, Y e W
      Se a espécie for do tipo processo, deve indicar o volume do mesmo, iniciando com a letra V + um número de dois dígitos  
    examples: 
      - A      (Ex. para um documento de sigla PDMEM202012345 - Memorando)
      - V01    (Ex. para um documento de sigla PDPRC202012345 - Processo)
    type: string
    required: true
  completo:
    name: completo
    in: query
    description: Informar true se deseja receber todos os arquivos juntados e anexos
    required: false
    default: false
    type: boolean
  estampa:
    name: estampa
    in: query
    description: Informar true se deseja receber o PDF sem estampas
    required: false
    default: false
    type: boolean
  volumes:
    name: volumes
    in: query
    description: Informar true se deseja receber uma compilação com todos os volumes de um processo
    required: false
    default: false
    type: boolean
  exibirreordenacao:
    name: exibirReordenacao
    in: query
    description: Exibir reordenação
    required: false
    type: boolean
  pdf:
    name: pdf
    in: path
    description: Referência para o PDF que foi enviado previamente para o servidor
    type: string
    required: true
  jwt:
    name: jwt
    in: path
    description: JWT que referencia um artefato a ser baixado
    required: true
    type: string
  filename:
    name: filename
    in: path
    description: Nome do arquivo de um artefato a ser baixado
    required: true
    type: string
  disposition:
    name: disposition
    in: query
    description: Informar attachment se desejar receber como um download
    required: false
    type: string
  contenttype:
    name: contenttype
    in: query
    description: Informar o tipo de arquivo desejado, pode ser application/pdf ou text/html
    required: false
    type: string
    enum: [application/pdf, text/html]
  chave:
    name: chave
    in: path
    description: Chave que referencia um processo assíncrono
    required: true
    type: string
  siglapai:
    name: siglapai
    in: body
    description: 
      Sigla do documento pai a ser juntado com a indicação da via ou volume (mobil).
    examples:
      - PD-EXP-2020/12345A
      - SAAMEM201912345B
      - GOVPRC201912345V01
    type: string
    required: true
  exibirReordenacao:
    name: exibirReordenacao
    in: query
    description: Informar true se deseja ????????????
    required: false
    default: false
    type: boolean
    


################################################################################
#                                           Paths                              #
################################################################################
paths:
  /autenticar:
    post:
      summary: Recebe login e senha e gera um token JWT para ser usado nos outros métodos da API
      tags: [auth]
      security:
        - Basic: []
      parameters: []
      responses:
        200:
          description: Successful response
          schema:
            type: object
            properties:
              token:
                type: string
                description: Token JWT
        500:
          description: Error ocurred
          schema:
            $ref: "#/definitions/Error"
  /documento/{sigla}/arquivo:
    get:
      summary: Inicia o processo de geração do PDF completo de um documento para visualização
      tags: [download]
      security:
        - Bearer: []
      parameters:
        - $ref: "#/parameters/contenttype"
        - $ref: "#/parameters/sigla"
        - $ref: "#/parameters/estampa"
        - $ref: "#/parameters/completo"
        - $ref: "#/parameters/volumes"
        - $ref: "#/parameters/exibirReordenacao"
      responses:
        200:
          description: Successful response
          schema:
            type: object
            properties:
              uuid:
                type: string
                description: UUID que pode ser usado como chave para obter status da geração do PDF
              jwt:
                type: string
                description: JWT com as informações para download do PDF
        404:
          description: Número do Documento não existe no SPSP
          schema:
            type: string # código do documento não encontrado
        500:
          description: Error ocurred
          schema:
            $ref: "#/definitions/Error"

  /download/{jwt}/{filename}:
    get:
      summary: Faz o download de um artefato qualquer, baseado nas informações contidas em um JWT
      tags: [download]
      parameters:
        - $ref: "#/parameters/jwt"
        - $ref: "#/parameters/filename"
        - $ref: "#/parameters/disposition"
      responses:
        200:
          description: Successful response
          schema:
            type: file
          headers:
            Content-Type:
              type: string
              description: application/pdf
            Content-Disposition:
              type: string
              description: attachment
        404:
          description: Documento Não encontrado
          schema:
            type: string # código do documento não encontrado
        500:
          description: Error ocurred
          schema:
            $ref: "#/definitions/Error"
            
  /status/{chave}:
    get:
      tags: [download]
      parameters:
        - $ref: "#/parameters/chave"
      summary: Obtem o status de uma operação assíncrona
      responses:
        200:
          description: Successful response
          schema:
            type: object
            properties:
              mensagem:
                type: string
                description: Mensagem
              indice:
                type: number
                description: Quantos passos já foram executados
              contador:
                type: number
                description: Número total de passos a serem executados
              bytes:
                type: number
                description: Tamanho total do payload até o momento
              errormsg:
                type: string
                description: Mensagem de erro se houver
              stacktrace:
                type: string
                description: Detalhamento do erro
        500:
          description: Error ocurred
          schema:
            $ref: "#/definitions/Error"

  /documento/{sigladoc}/mobil/{siglamob}/juntar:
    post:
      summary: Junta a via de um documento com outro informado em siglapai
      tags: [mobil]
      security:
        - Bearer: []
      consumes: 
        - application/json
      produces: 
        - application/json
      parameters:
        - $ref: "#/parameters/sigladoc"
        - $ref: "#/parameters/siglamob"
        - name: body
          in: body
          type: string
          description: Parâmetros para juntada.
            siglapai = Sigla do documento pai a ser juntado com a indicação da via ou volume (mobil). Ex. GOVPRC201912345V01 
          required: true
          schema:
            properties: 
              siglapai:
                type: string
      responses:
        200:
          description: Successful response
          schema:
            type: object
        403:
          description: Acesso ao documento não permitido
          schema:
            $ref: "#/definitions/Error"
        404:
          description: Via ou volume não encontrado
          schema:
            $ref: "#/definitions/Error"
        500:
          description: Erro na juntada
          schema:
            $ref: "#/definitions/Error"

  /mobil/assinar/{sigla}:
    post:
      summary: Assina um documento
      tags: [mobil]
      security:
        - Bearer: []
      parameters:
        - $ref: "#/parameters/sigla"
      responses:
#Tive que adicionar o 200 porque se tivesse apenas o 201 swaggerservlet soltaria uma exceção
        200:
          description: Ok
        201:
          description: Assinado
          schema: 
            type: object
            properties:
              numeroReferencia:
                type: string
                description:  Número de Referência
        400:
          description: Erro de Validação
        403: 
          description: Documento <número do documento> Sem Permissão para Assinar
        404:
          description: Número dos Documento não existe no SPSP
        500:
          description: Error ocurred
          schema:
            $ref: "#/definitions/Error"

  /mobil/autenticar/{sigla}:
    post:
      summary: Autentica um documento
      tags: [mobil]
      security:
        - Bearer: []
      parameters:
        - $ref: "#/parameters/sigla"
      responses:
#Tive que adicionar o 200 porque se tivesse apenas o 201 swaggerservlet soltaria uma exceção
        200:
          description: Ok
        201:
          description: Autenticado
          schema: 
            type: object
            properties:
              numeroReferencia:
                type: string
                description:  Número de Referência
        400:
          description: Erro de Validação
        403: 
          description: Documento <número do documento> Sem Permissão para Assinar
        404:
          description: Número dos Documento não existe no SPSP
        500:
          description: Error ocurred
          schema:
            $ref: "#/definitions/Error"

################################################################################
#                                     Definitions                              #
################################################################################
definitions:
  Status:
    type: object
    properties:
      mensagem:
        type: string
        description: Mensagem
      indice:
        type: number
        description: Quantos passos já foram executados
      contador:
        type: number
        description: Número total de passos a serem executados
      bytes:
        type: number
        description: Tamanho total do payload até o momento
      errormsg:
        type: string
        description: Mensagem de erro se houver
      stacktrace:
        type: string
        description: Detalhamento do erro

  Error:
    type: object
    properties:
      errormsg:
        type: string